# ver si usar un enum

OK = 11
MSG_FORMAT_ERROR = 12
SYNTAX_ERROR = 13
PARAMETER_SET_IN_SERVER_FAILED = 14

TEMPERATURE_DEPENDENT_OUTPUT_ELECTRICALLY_ON = 51
TEMPERATURE_DEPENDENT_OUTPUT_ELECTRICALLY_OFF = 52

MANUAL_ON = 101
TIME_ON = 102

OUTPUT_MODIFICATION_FAILED_LEVEL = 111
OUTPUT_MODIFICATION_FAILED_ON_TIME_SURPASSED = 112
OUTPUT_MODIFICATION_FAILED_MAX_ENERGY_SURPASSED = 113
OUTPUT_MODIFICATION_FAILED_ELECTRIC_FAILURE = 114

OUTPUT_ADDED_BY_USER = 201
OUTPUT_ADDED_CONFIRMED_BY_DEVICE = 202
OUTPUT_DELETED_BY_USER = 203
OUTPUT_DELETED_CONFIRMED_BY_DEVICE = 204
OUTPUT_PARAMETERS_CHANGED_BY_USER = 205
OUTPUT_PARAMETERS_CHANGED_CONFIRMED_BY_DEVICE = 206
TEMPERATURE_SET_BY_USER = 207
TEMPERATURE_CONFIRMED_BY_DEVICE = 208

WORKING_TIME_AND_TEMPERATURE_GET_FROM_DEVICE = 211
WORKING_TIME_AND_TEMPERATURE_GOT_FROM_DEVICE = 212
ALL_PARAMETERS_GET_FROM_DEVICE = 213
ALL_PARAMETERS_GOT_FROM_DEVICE = 214
UNLINK = 215
UNLINK_CONFIRMED_BY_DEVICE = 216
UNLINK_CONFIRMED_BY_SERVER = 217
